// johnny/Angular/busreservationsystem/src/app/bookingdetails/bookingdetails.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-bookingdetails',
  templateUrl: './bookingdetails.component.html',
  styleUrls: ['./bookingdetails.component.css']
})
export class BookingdetailsComponent {
  form: FormGroup;
  currentDate: string;

  constructor(private fb: FormBuilder) {
    this.currentDate = new Date().toISOString().split('T')[0];
    this.form = this.fb.group({
      origin: ['', Validators.required],
      destination: ['', [Validators.required], this.validateOriginDestination],
    })
    

  }

  validateOriginDestination() {

    const originValue = this.form.get('origin')?.value;

    const destinationValue = this.form.get('destination')?.value;
    console.log(originValue + "\t\t" + destinationValue);

    if (originValue === destinationValue) {
      alert("Origin and destination should not be the same!");
      const destinationInput = document.getElementById("destination") as HTMLInputElement;
      if (destinationInput) {
        destinationInput.focus();
      }
    }
  }
  
  onSubmit() {
    alert("Submited...");
  }

}


<body><br><br>
  <h1>BOOKING DETAILS</h1><br>
<form [formGroup]="form" (ngSubmit)="onSubmit()">
  <label for="passengerName" class="lable"><h3><b>Passenger Name</b></h3></label>
  <input type="text" id="passengerName" name="passenger" class="text" formControlName="passengerName" /><br><br>

  <label for="journeyDate" class="lable"><h3><b>Journey Date</b></h3></label>
  <input
    type="date"
    id="journeyDate"
    class="text"
    name="date"
    [min]="currentDate"
    formControlName="journeyDate"
  /><br><br>

  <label for="origin" class="lable"><h3><b>Origin</b></h3></label>
  <select id="origin" class="text" name="origin" >
    <option value="Chennai" selected>Chennai</option>
    <option value="Bangalore">Bangalore</option>
    <option value="Trichy">Trichy</option>
    <option value="Rameshwaram">Rameshwaram</option>
  </select><br><br>
  

  <label for="destination" class="lable"><h3><b>Destination</b></h3></label>
  <select id="destination" class="text" name="dest" formControlName="destination" (change)="this.validateOriginDestination()"> 
    <option value="Chennai">Chennai</option>
    <option value="Bangalore" selected>Bangalore</option>
    <option value="Trichy">Trichy</option>
    <option value="Rameshwaram">Rameshwaram</option><br>
  </select><br><br>

  <a routerLink="/bookedTable"><button type="submit" class="button" value="submit"><b>Submit</b></button> </a>
</form>

</body>
<router-outlet></router-outlet>

// johnny/React/busreservationsystem/src/component/BookingDetails.js
import { Component } from "react";
import { Link } from "react-router-dom";

class BookingDetails extends Component {
  constructor(props) {
    super(props);
    this.state = {
      passengername: "",
      origin: "",
      destination: "",
      startDate: "",
      disable: true,
    };
  }
  componentDidMount() {
     const passengername = sessionStorage.getItem('getName');
     const origin = sessionStorage.getItem("origin");
     const destination = sessionStorage.getItem("destination");
     const startDate = sessionStorage.getItem("startDate");

    if (passengername) {
      this.setState({ passengername });
    }
    if (origin) {
      this.setState({ origin });
    }
    if (destination) {
      this.setState({ destination });
    }
    if (startDate) {
      this.setState({ startDate });
     
    }
  }
  componentWillUnmount() {
    
    sessionStorage.removeItem("origin");
    sessionStorage.removeItem("destination");
    sessionStorage.removeItem("startDate");
  }
  // const [passengername, setName] = useState("");
 
  // const [journeydate, setDate] = useState("");
  // const [originplace, setOriginplace] = useState("");
  // const [destinationplace, setDestinationplace] = useState("");

  validate = (event) => {
    event.preventDefault(); 
    let submitOK = true;

    if (this.state.passengername.length > 10) {
      alert("The name must be less than 10 characters");
      submitOK = false;
    }
    

    this.setState({ disable: !submitOK });
  };

  check = () => {
    
    if (this.state.origin === this.state.destination) {
      this.setState({ disable: true });
      alert("Destination and origin should not be the same");
    } else {
      this.setState({ disable: false });
    }
  };

  handleNameChange = (event) => {
    this.setState({ passengername: event.target.value });
  };

  // handleDateChange = (event) => {
  //   this.setState({ startDate: event.target.value });
  // };

  handleOriginChange = (event) => {
    this.setState({ origin: event.target.value }, () => {
      this.check(); // Call check() after updating origin
      sessionStorage.setItem("origin", this.state.origin);
    });
    
  };

  handleDestinationChange = (event) => {
    this.setState({ destination: event.target.value }, () => {
      this.check(); // Call check() after updating destination
      sessionStorage.setItem("destination", this.state.destination);
      
    });
    
  };

  handleDateChange=(event)=>{
    this.setState({ startDate: event.target.value },()=>{
      sessionStorage.setItem("startDate", this.state.startDate);
    }
    );
  };
  successful=()=>{
    alert('Your booking has been successfully created');
  };

  render() {
    const today = new Date().toISOString().split("T")[0];
    
    return (
      <div>
        <center>
          <form onSubmit={this.validate}>
          <b className="titleStyle">Booking Details</b><br></br>
            <label className="labelStyle">
              <b>Name : </b>{" "}
            </label >
            <input
              type="text"
              id="passengername"
              placeholder="Enter your name"
              className="inputStyle"
              value={this.state.passengername}
              onChange={this.handleNameChange}
            />
            <br></br>
            <label className="labelStyle">
              <b>Journey Date : </b>
            </label>
            <input
              type="date"
              id="date"
              name="date"
              className="inputStyle"
              value={this.state.startDate}
              onChange={this.handleDateChange}
              min={today}
              required
              
              
            />
            <br></br>
            <label className="labelStyle">
              <b>Origin : </b>
            </label>
            <select
              id="origin"
              className="inputStyle"
              
              value={this.state.origin}
              onChange={this.handleOriginChange}
            
            >
              <option value="">Select a Origin place</option>
              <option value="Chennai">Chennai</option>
              <option value="Bangalore">Bangalore</option>
              <option value="Trichy">Trichy</option>
              <option value="Rameshwaram">Rameshwaram</option>
            </select>
            <br></br>
            <label className="labelStyle">
              <b>Destination : </b>
            </label>
            <select
              id="destination"
              className="inputStyle"
              value={this.state.destination}
              onChange={this.handleDestinationChange}
            >
              <option value="">Select a Destination place</option>
              <option value="Chennai">Chennai</option>
              <option value="Bangalore">Bangalore</option>
              <option value="Trichy">Trichy</option>
              <option value="Rameshwaram">Rameshwaram</option>
            </select>
            <br></br><br></br>
            <Link to="/BookingTable">
              <input
                type="submit"
                id="submit"
                value="Add"
                className="buttonStyle" 
                disabled={this.state.disable}
                onClick={this.successful}
              />
            </Link>

            <input type="reset" value="Reset" className="buttonStyle" />
          </form>
        </center>
      </div>
    );
  }
}

export default BookingDetails;
